/* C ABI for the Anki iOS bridge (bridge/src/lib.rs).
 *
 * All request/response payloads are protobuf-encoded bytes; the message
 * types are defined in /home/ramon/anki/proto/anki/ and mirrored on the
 * Swift side by swift-protobuf generated code.
 */

#ifndef ANKI_BRIDGE_H
#define ANKI_BRIDGE_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Opaque handle to an open backend. */
typedef struct AnkiBackend AnkiBackend;

/* Open a backend from a serialised anki.backend.BackendInit message.
 * Returns NULL on failure. The returned handle must be released with
 * anki_close_backend. */
AnkiBackend *anki_open_backend(const uint8_t *init_msg, size_t len);

/* Dispatch a protobuf RPC. `service`/`method` are the integer indices from
 * the generated dispatch table (see ServiceIndex.swift, generated by
 * scripts/gen-swift-proto.sh from the same descriptor pool rslib uses).
 *
 * Returns 0 on success (out = response proto), -1 on error
 * (out = anki.backend.BackendError proto). In both cases *out must be
 * released with anki_free_bytes(*out, *out_len). */
int32_t anki_run_method(AnkiBackend *backend, uint32_t service, uint32_t method,
                        const uint8_t *input, size_t len,
                        uint8_t **out, size_t *out_len);

/* Free a buffer returned by anki_run_method. */
void anki_free_bytes(uint8_t *ptr, size_t len);

/* Close the backend and free all associated resources. */
void anki_close_backend(AnkiBackend *backend);

/* Start the local web server that serves the Svelte pages and media to
 * WKWebViews. `web_root` is a NUL-terminated UTF-8 path to the compiled
 * web assets. Returns the loopback port, or 0 on failure.
 * NOT YET IMPLEMENTED — Phase 3. */
uint16_t anki_start_mediasrv(AnkiBackend *backend, const char *web_root);

#ifdef __cplusplus
}
#endif

#endif /* ANKI_BRIDGE_H */
