// C ABI bridge between the iOS Swift shell and Anki's Rust core (rslib).
//
// Design mirrors pylib/rsbridge/lib.rs but uses a plain C ABI instead of PyO3,
// because the Swift side communicates via raw protobuf bytes (no typed bindings
// needed — swift-protobuf handles encoding/decoding on the Swift side).
//
// Error convention for anki_run_method:
//   return 0  → success; *out / *out_len contain the response proto bytes.
//   return -1 → error;   *out / *out_len contain a BackendError proto bytes.
// In both cases the caller must pass the buffer back to anki_free_bytes when
// done.

use std::ffi::c_char;

use anki::backend::init_backend;
use anki::backend::Backend;

// ---------------------------------------------------------------------------
// Public C ABI
// ---------------------------------------------------------------------------

/// Open a backend from a serialised `anki_proto::backend::BackendInit` message.
/// Returns a heap-allocated Backend on success, or null on failure.
/// The caller owns the returned pointer and must eventually pass it to
/// `anki_close_backend`.
#[no_mangle]
pub extern "C" fn anki_open_backend(init_msg: *const u8, len: usize) -> *mut Backend {
    if init_msg.is_null() {
        return std::ptr::null_mut();
    }
    let bytes = unsafe { std::slice::from_raw_parts(init_msg, len) };
    match init_backend(bytes) {
        Ok(backend) => Box::into_raw(Box::new(backend)),
        Err(_) => std::ptr::null_mut(),
    }
}

/// Dispatch a protobuf RPC call to the backend.
///
/// `service` and `method` are the integer indices generated by the rslib build
/// (see OUT_DIR/backend.rs).  The request is `input[..len]`.  On return,
/// `*out` points to a freshly heap-allocated buffer of `*out_len` bytes
/// (either the response proto or a BackendError proto).
///
/// Returns 0 on success, -1 on error (BackendError in *out/*out_len).
/// The caller must pass *out to `anki_free_bytes(*out, *out_len)` when done.
#[no_mangle]
pub extern "C" fn anki_run_method(
    backend: *mut Backend,
    service: u32,
    method: u32,
    input: *const u8,
    len: usize,
    out: *mut *mut u8,
    out_len: *mut usize,
) -> i32 {
    if backend.is_null() || out.is_null() || out_len.is_null() {
        return -1;
    }
    let backend = unsafe { &*backend };
    let in_bytes = unsafe { std::slice::from_raw_parts(input, len) };

    let (bytes, rc) = match backend.run_service_method(service, method, in_bytes) {
        Ok(v) => (v, 0),
        Err(v) => (v, -1),
    };
    write_output(bytes, out, out_len);
    rc
}

/// Free a buffer previously returned via `anki_run_method`.
#[no_mangle]
pub extern "C" fn anki_free_bytes(ptr: *mut u8, len: usize) {
    if ptr.is_null() {
        return;
    }
    unsafe {
        drop(Vec::from_raw_parts(ptr, len, len));
    }
}

/// Close the backend and free all associated resources.
#[no_mangle]
pub extern "C" fn anki_close_backend(backend: *mut Backend) {
    if !backend.is_null() {
        unsafe { drop(Box::from_raw(backend)) };
    }
}

/// Start the local HTTP server that serves the Svelte web pages to WKWebViews.
/// `web_root` is the path to the compiled web assets directory
/// (AnkiIOS/Resources/web/).
///
/// Returns the port the server is listening on, or 0 on failure.
///
/// NOTE: Not yet implemented — Phase 3 task.  The desktop media server is a
/// Python Flask/waitress process (qt/aqt/mediasrv.py); on iOS we need an
/// equivalent Rust axum server (rslib already depends on axum) that serves
/// the same /_anki/ routes.  This stub exists so the C header and Swift
/// wrapper can be written against the final ABI now.
#[no_mangle]
pub extern "C" fn anki_start_mediasrv(_backend: *mut Backend, _web_root: *const c_char) -> u16 {
    // TODO(Phase 3): implement an axum-based local HTTP server that:
    //   - serves static files from web_root under /_anki/
    //   - handles POST /_anki/<service>/<method> by calling anki_run_method
    //   - serves media files from the collection's media folder
    //   - returns the ephemeral loopback port it bound to
    0
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

fn write_output(bytes: Vec<u8>, out: *mut *mut u8, out_len: *mut usize) {
    let len = bytes.len();
    let mut bytes = bytes.into_boxed_slice();
    let ptr = bytes.as_mut_ptr();
    std::mem::forget(bytes);
    unsafe {
        *out = ptr;
        *out_len = len;
    }
}

// ---------------------------------------------------------------------------
// Tests — host-side (Linux/macOS), no iOS target required
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use prost::Message;

    fn make_init_bytes() -> Vec<u8> {
        anki_proto::backend::BackendInit {
            preferred_langs: vec!["en".to_string()],
            ..Default::default()
        }
        .encode_to_vec()
    }

    #[test]
    fn open_and_close_backend() {
        let init = make_init_bytes();
        let backend = anki_open_backend(init.as_ptr(), init.len());
        assert!(!backend.is_null(), "init_backend returned null");
        anki_close_backend(backend);
    }

    // Service/method indices below were read from the generated dispatch code
    // (OUT_DIR/backend.rs, produced by rslib's build script from the proto
    // descriptor pool).  Backend services have odd indices; collection-level
    // services the even ones.  These must stay in sync with the Swift enum
    // generated in Phase 2 (scripts/gen-swift-proto.sh derives both from the
    // same source).
    const SERVICE_BACKEND_COLLECTION: u32 = 3;
    const METHOD_OPEN_COLLECTION: u32 = 0;
    const SERVICE_BACKEND_DECKS: u32 = 7;
    const METHOD_DECK_TREE: u32 = 4;

    fn run_ffi(
        backend: *mut Backend,
        service: u32,
        method: u32,
        input: &[u8],
    ) -> (i32, Vec<u8>) {
        let mut out: *mut u8 = std::ptr::null_mut();
        let mut out_len: usize = 0;
        let rc = anki_run_method(
            backend,
            service,
            method,
            input.as_ptr(),
            input.len(),
            &mut out,
            &mut out_len,
        );
        let bytes = unsafe { std::slice::from_raw_parts(out, out_len) }.to_vec();
        anki_free_bytes(out, out_len);
        (rc, bytes)
    }

    /// Phase 1 success criterion: open a backend, create a collection in a
    /// temp dir, and run a deck_tree RPC — all through the C ABI.
    #[test]
    fn open_collection_and_deck_tree() {
        let dir = tempfile::tempdir().unwrap();
        let media_dir = dir.path().join("collection.media");
        std::fs::create_dir_all(&media_dir).unwrap();

        let init_bytes = make_init_bytes();
        let backend = anki_open_backend(init_bytes.as_ptr(), init_bytes.len());
        assert!(!backend.is_null());

        let open_req = anki_proto::collection::OpenCollectionRequest {
            collection_path: dir
                .path()
                .join("collection.anki2")
                .to_str()
                .unwrap()
                .to_string(),
            media_folder_path: media_dir.to_str().unwrap().to_string(),
            media_db_path: dir
                .path()
                .join("collection.media.db")
                .to_str()
                .unwrap()
                .to_string(),
        };
        let (rc, err) = run_ffi(
            backend,
            SERVICE_BACKEND_COLLECTION,
            METHOD_OPEN_COLLECTION,
            &open_req.encode_to_vec(),
        );
        assert_eq!(
            rc,
            0,
            "OpenCollection failed: {:?}",
            anki_proto::backend::BackendError::decode(err.as_slice())
        );

        let deck_tree_req = anki_proto::decks::DeckTreeRequest { now: 1 };
        let (rc, out) = run_ffi(
            backend,
            SERVICE_BACKEND_DECKS,
            METHOD_DECK_TREE,
            &deck_tree_req.encode_to_vec(),
        );
        assert_eq!(
            rc,
            0,
            "DeckTree failed: {:?}",
            anki_proto::backend::BackendError::decode(out.as_slice())
        );
        let tree = anki_proto::decks::DeckTreeNode::decode(out.as_slice()).unwrap();
        // A fresh collection contains the single "Default" deck under the root.
        assert_eq!(tree.children.len(), 1);

        anki_close_backend(backend);
    }
}
