//! Emit ServiceIndex.swift: the service/method indices the Swift
//! BackendClient passes to anki_run_method.
//!
//! Uses anki_proto_gen::get_services over the same descriptor pool rslib's
//! build script uses for its dispatch table (OUT_DIR/backend.rs), so the
//! indices cannot desync from the Rust side.

use inflections::Inflect;
use prost_reflect::DescriptorPool;

fn main() {
    let pool = DescriptorPool::decode(
        include_bytes!(concat!(env!("OUT_DIR"), "/descriptors.bin")).as_ref(),
    )
    .expect("decode descriptor pool");

    // Client code uses the backend services only (see proto_gen docs).
    let (_, backend_services) = anki_proto_gen::get_services(&pool);

    println!("// Generated by tools/gen-service-index — do not edit.");
    println!("// Regenerate with scripts/gen-swift-proto.sh.");
    println!();
    println!("public enum AnkiServiceIndex {{");
    for service in &backend_services {
        if service.name == "BackendFrontendService" {
            continue;
        }
        let swift_name = service.name.trim_start_matches("Backend");
        println!("    public enum {swift_name} {{");
        println!(
            "        public static let service: UInt32 = {}",
            service.index
        );
        for method in service.all_methods() {
            println!(
                "        public static let {}: UInt32 = {}",
                method.name.to_camel_case(),
                method.index
            );
        }
        println!("    }}");
    }
    println!("}}");
}
